In [ ]:
#creating multiple arrays and multi dimensional arrays and introducing data analysis

In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
#creating a 1D simple array
array =np.array([1, 2, 3, 4, 5])

In [5]:
#arrays don't have commas like lists do!!!
print(array)

[1 2 3 4 5]


In [7]:
#let's explore the different size dimensions
#0 dimensional array
zero_dim = np.array(69696969)
print(zero_dim)

69696969


In [8]:
#1 dimensional array
one_dim = np.array([1, 2, 3])
print(one_dim)

[1 2 3]


In [10]:
#2 dimensional array. Always add in the extra brackets
two_dim = np.array([[1, 2, 3], [4, 5, 6]])
print(two_dim)

[[1 2 3]
 [4 5 6]]


In [12]:
#3 dimensional array. 
three_dim = np.array([[[1, 2, 3], [4, 5 ,6]], [[7, 8, 9], [10, 11, 12]]])
print(three_dim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
#finding the dimension of a given array
print(three_dim.ndim)

3


In [15]:
#create specific dimensional arrays. This creates a 5 dimensional array. no. of brackets shows how many dimension array it is
new_array = np.array(17, ndmin=5)
print(new_array)

[[[[[17]]]]]


In [17]:
new_array1 = np.array([1,2,3], ndmin=5)
print(new_array1)

[[[[[1 2 3]]]]]


In [ ]:
#[::-1]: Reverses the array along the specified axis (for 1D arrays).
#[::-1, :]: Reverses the rows of a 2D array.
#[:, ::-1]: Reverses the columns of a 2D array.
#[::-1, ::-1]: Reverses both the rows and columns of a 2D array.