In [1]:
#NumPy is a python libray allowing working with big and small arrays. 
#has support for N-dimensional arrays so you can work w arrays w/in an array
#Useful for working w a large majority of data science tools or deep learning libraries like Pandas and Tensorflow 
#this tutorial covers working with installing NumPy, 1 creating 2 reading 3 updating (mathematical functions) and 4 deleting numpy arrays, and also exporting your work


In [2]:
#install and importing numpy
!pip install numpy

In [3]:
#import into notebook 
import numpy as np

In [5]:
#Creating some Numpy arrays
#randomly generated array
data = np.random.rand(2,3,4)
#creates an array full of zeroes
zeroes = np.zeros((2,2,2))
#similar to np.zeros function, but replacing 0 w/ 7's
full = np.full ((2,2,2), 7)
#similar to zeroes and full, but replacing values w 1's
ones = np.ones((2,2,2))


In [12]:
data

array([[[0.62012261, 0.77687687, 0.64400784, 0.60555457],
        [0.52998648, 0.54962063, 0.5327671 , 0.4167441 ],
        [0.14924644, 0.96335667, 0.07417496, 0.02528755]],

       [[0.67731824, 0.23021081, 0.12848109, 0.97655006],
        [0.40597107, 0.70145499, 0.47667462, 0.61036087],
        [0.24900544, 0.09489444, 0.13129735, 0.35360268]]])

In [16]:
zeroes = np.zeros((2,2,2))
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [19]:
full = np.full ((2,2,2), 7)
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [21]:
ones = np.ones((2,2,2))
ones


array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [22]:
#Reading Arrays
#3 different attributes
shape = data.shape
size = data.size
types = data.dtype

In [23]:
#shape of array
#refer to data array above for accessing shapes 2 (2 different arrays), 3 (arrays ), 4 (number of values)
shape

(2, 3, 4)

In [24]:
#size of arrays
#24 values w/ in the array
size

24

In [25]:
#types of values w/in the arrays
types

dtype('float64')

In [26]:
#slicing arrays
arr=data[0]
slicer = data[0:2]
reverse = data[-1]
singleval = data [0][0][0]

In [27]:
#will grab first array of 3 values
arr

array([[0.62012261, 0.77687687, 0.64400784, 0.60555457],
       [0.52998648, 0.54962063, 0.5327671 , 0.4167441 ],
       [0.14924644, 0.96335667, 0.07417496, 0.02528755]])

In [28]:
#slicer to grab multiple values. this grabs the first and 2nd
slicer

array([[[0.62012261, 0.77687687, 0.64400784, 0.60555457],
        [0.52998648, 0.54962063, 0.5327671 , 0.4167441 ],
        [0.14924644, 0.96335667, 0.07417496, 0.02528755]],

       [[0.67731824, 0.23021081, 0.12848109, 0.97655006],
        [0.40597107, 0.70145499, 0.47667462, 0.61036087],
        [0.24900544, 0.09489444, 0.13129735, 0.35360268]]])

In [29]:
#this grabs the first array and the first two arrays w/ in the first array
slicer = data[0][0:2]
slicer

array([[0.62012261, 0.77687687, 0.64400784, 0.60555457],
       [0.52998648, 0.54962063, 0.5327671 , 0.4167441 ]])

In [30]:
#grabbing the last value or this grabs the last arrays
reverse

array([[0.67731824, 0.23021081, 0.12848109, 0.97655006],
       [0.40597107, 0.70145499, 0.47667462, 0.61036087],
       [0.24900544, 0.09489444, 0.13129735, 0.35360268]])

In [32]:
#grabbing a single value w/ in 1st array, first array within the 1st array, and the 1st value
singleval

0.6201226075473506

In [34]:
data

array([[[0.62012261, 0.77687687, 0.64400784, 0.60555457],
        [0.52998648, 0.54962063, 0.5327671 , 0.4167441 ],
        [0.14924644, 0.96335667, 0.07417496, 0.02528755]],

       [[0.67731824, 0.23021081, 0.12848109, 0.97655006],
        [0.40597107, 0.70145499, 0.47667462, 0.61036087],
        [0.24900544, 0.09489444, 0.13129735, 0.35360268]]])

In [36]:
#Updating Arrays
lists1 = np.random.rand(10)
lists2 = np.random.rand(10)

In [40]:
#Has 10 values in a single array
lists1

array([0.85596845, 0.70309847, 0.86083656, 0.12503127, 0.17332468,
       0.13742207, 0.75737299, 0.66966071, 0.77441713, 0.42601816])

In [43]:
#basic math
add = np.add(lists1, lists2)
sub = np.subtract(lists1, lists2)
div = np.divide(lists1, lists2)
mult = np.multiply(lists1, lists2)
dot = np.dot(lists1, lists2)

In [41]:
lists2

array([0.65015647, 0.89723261, 0.42051528, 0.15886555, 0.53724573,
       0.33858104, 0.71486604, 0.38885572, 0.68759924, 0.11097323])

In [42]:
add

array([1.50612492, 1.60033108, 1.28135184, 0.28389682, 0.71057041,
       0.47600311, 1.47223903, 1.05851643, 1.46201636, 0.53699139])

In [44]:
sub

array([ 0.20581198, -0.19413414,  0.44032128, -0.03383428, -0.36392105,
       -0.20115897,  0.04250695,  0.28080499,  0.08681789,  0.31504493])

In [45]:
div

array([1.31655762, 0.78363009, 2.04709937, 0.78702568, 0.32261713,
       0.40587645, 1.05946142, 1.72213157, 1.12626235, 3.83892724])

In [46]:
mult

array([0.55651343, 0.63084287, 0.36199493, 0.01986316, 0.09311794,
       0.04652851, 0.54142023, 0.2604014 , 0.53248863, 0.04727661])

In [47]:
#multiplies every value together and aggregates them into a single result
dot

3.090447700449392

In [49]:
#statistical functions using np
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(lists1)
maxs = np.max(lists1)

In [ ]:
#Remember SAPLEMM for all stat functions (above)

In [50]:
#square root of 25
sqrt

5.0

In [51]:
#getting absolute value of -2
ab

2

In [53]:
#calculating power, for example 2 to the power of 7
power

128

In [54]:
#calculating the log of 25
log

3.2188758248682006

In [56]:
#creating exponential
exp

[2, 3]

In [58]:
#min and max of lists1
min

<function min>

In [61]:
lists1 = np.random.rand(10)
lists2 = np.random.rand(10)

In [62]:
#min and max of lists1
mins = np.min(lists1)
maxs = np.max(lists1)

In [63]:
mins

0.18591015114277631

In [65]:
maxs

0.7368173836704046

In [66]:
lists1

array([0.71521771, 0.38034958, 0.53767042, 0.60745282, 0.51143208,
       0.65214961, 0.73681738, 0.18591015, 0.66628255, 0.56895985])

In [67]:
data

array([[[0.62012261, 0.77687687, 0.64400784, 0.60555457],
        [0.52998648, 0.54962063, 0.5327671 , 0.4167441 ],
        [0.14924644, 0.96335667, 0.07417496, 0.02528755]],

       [[0.67731824, 0.23021081, 0.12848109, 0.97655006],
        [0.40597107, 0.70145499, 0.47667462, 0.61036087],
        [0.24900544, 0.09489444, 0.13129735, 0.35360268]]])

In [68]:
#replace the very first value, in the first array, and the first array w/in that array 
data[0][0][0] = 700

In [69]:
data

array([[[7.00000000e+02, 7.76876873e-01, 6.44007836e-01, 6.05554570e-01],
        [5.29986479e-01, 5.49620633e-01, 5.32767100e-01, 4.16744101e-01],
        [1.49246436e-01, 9.63356673e-01, 7.41749598e-02, 2.52875470e-02]],

       [[6.77318238e-01, 2.30210812e-01, 1.28481089e-01, 9.76550061e-01],
        [4.05971071e-01, 7.01454994e-01, 4.76674618e-01, 6.10360867e-01],
        [2.49005440e-01, 9.48944397e-02, 1.31297351e-01, 3.53602678e-01]]])

In [70]:
#sorting our data. This sorts our data in each arrays within arrays from smallest to greatest values
data.sort()
data

array([[[6.05554570e-01, 6.44007836e-01, 7.76876873e-01, 7.00000000e+02],
        [4.16744101e-01, 5.29986479e-01, 5.32767100e-01, 5.49620633e-01],
        [2.52875470e-02, 7.41749598e-02, 1.49246436e-01, 9.63356673e-01]],

       [[1.28481089e-01, 2.30210812e-01, 6.77318238e-01, 9.76550061e-01],
        [4.05971071e-01, 4.76674618e-01, 6.10360867e-01, 7.01454994e-01],
        [9.48944397e-02, 1.31297351e-01, 2.49005440e-01, 3.53602678e-01]]])

In [71]:
print(data.shape)

(2, 3, 4)


In [72]:
#reshaping a np array
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [73]:
#reshaped our data to 2 arrays per 2 different array. -1 tells us we don't care what the shape of the last value is
#so it's automatically calculated that it needs to be 6 values per arrays
data

array([[[6.05554570e-01, 6.44007836e-01, 7.76876873e-01, 7.00000000e+02,
         4.16744101e-01, 5.29986479e-01],
        [5.32767100e-01, 5.49620633e-01, 2.52875470e-02, 7.41749598e-02,
         1.49246436e-01, 9.63356673e-01]],

       [[1.28481089e-01, 2.30210812e-01, 6.77318238e-01, 9.76550061e-01,
         4.05971071e-01, 4.76674618e-01],
        [6.10360867e-01, 7.01454994e-01, 9.48944397e-02, 1.31297351e-01,
         2.49005440e-01, 3.53602678e-01]]])

In [ ]:
#adding(append) or inserting new values working w numpy arrays


In [76]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print (zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [77]:
#inserting a value at a certain area
#we specified we want to insert a value of 1 in index 2 (or 3rd position)
zeroes=np.insert (zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


In [ ]:
#deleting a segment of an array and exporting out

In [78]:
data

array([[[6.05554570e-01, 6.44007836e-01, 7.76876873e-01, 7.00000000e+02,
         4.16744101e-01, 5.29986479e-01],
        [5.32767100e-01, 5.49620633e-01, 2.52875470e-02, 7.41749598e-02,
         1.49246436e-01, 9.63356673e-01]],

       [[1.28481089e-01, 2.30210812e-01, 6.77318238e-01, 9.76550061e-01,
         4.05971071e-01, 4.76674618e-01],
        [6.10360867e-01, 7.01454994e-01, 9.48944397e-02, 1.31297351e-01,
         2.49005440e-01, 3.53602678e-01]]])

In [ ]:
#delete the 1st array in each one of these arrays
#the axis=1 shows that we want to delete the row not the column, and 0 represents which array within the array we want to delete

In [83]:
delete = np.delete (data, 0, axis=1)

In [84]:
delete

array([[[0.5327671 , 0.54962063, 0.02528755, 0.07417496, 0.14924644,
         0.96335667]],

       [[0.61036087, 0.70145499, 0.09489444, 0.13129735, 0.24900544,
         0.35360268]]])

In [85]:
#this saves the new array in the same library as the notebook
np.save("new array", data)

In [86]:
#this loads the array
test = np.load("new array.npy")

In [87]:
test

array([[[6.05554570e-01, 6.44007836e-01, 7.76876873e-01, 7.00000000e+02,
         4.16744101e-01, 5.29986479e-01],
        [5.32767100e-01, 5.49620633e-01, 2.52875470e-02, 7.41749598e-02,
         1.49246436e-01, 9.63356673e-01]],

       [[1.28481089e-01, 2.30210812e-01, 6.77318238e-01, 9.76550061e-01,
         4.05971071e-01, 4.76674618e-01],
        [6.10360867e-01, 7.01454994e-01, 9.48944397e-02, 1.31297351e-01,
         2.49005440e-01, 3.53602678e-01]]])

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi