In [1]:
import numpy as np

In [2]:
current_age = input("current age is " )
print(current_age)

current age is  30


30


In [3]:
print(f"This year {current_age}")

This year 30


In [4]:
print(f"This year I just turned {current_age} years old.")

This year I just turned 30 years old.


In [9]:
#correct
#Create a 1D NumPy array containing the numbers from 10 to 19.
np_range_arr = np.array(range (10, 20))
np_range_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
#Create a 2D NumPy array of shape (4, 4) with numbers from 1 to 16.
#look up
twod_array = np.array(4, 4)
twod_array

TypeError: Cannot interpret '4' as a data type

In [18]:
#Add 5 to each element of the 1D array.
#correct
add_five = np.add(np_range_arr, 5)
add_five

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
#Access the third element of the 1D array.
#correct
np_range_arr[2]

12

In [20]:
#Slice the 1D array to get the elements from index 3 to 7.
#verify
np_range_arr[3:7]

array([13, 14, 15, 16])

In [21]:
#Calculate the sum of all elements in the 1D array.
#correct
np.sum(np_range_arr)

145

In [22]:
#Calculate the standard deviation of the 1D array.
#correct
np.std(np_range_arr)

2.8722813232690143

In [ ]:
SOLUTIONS to the exercises (including missing questions)

In [23]:
import numpy as np

# 1D array from 10 to 19
array_1d = np.arange(10, 20)
print("1D Array:", array_1d)

# 2D array of shape (4, 4) with numbers from 1 to 16
array_2d = np.arange(1, 17).reshape(4, 4)
print("2D Array:\n", array_2d)


1D Array: [10 11 12 13 14 15 16 17 18 19]
2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [24]:
# Add 5 to each element of the 1D array
array_1d_added = array_1d + 5
print("1D Array after adding 5:", array_1d_added)

# Multiply each element of the 2D array by 2
array_2d_multiplied = array_2d * 2
print("2D Array after multiplying by 2:\n", array_2d_multiplied)

1D Array after adding 5: [15 16 17 18 19 20 21 22 23 24]
2D Array after multiplying by 2:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [25]:
# Access the third element of the 1D array
third_element = array_1d[2]
print("Third element of the 1D array:", third_element)

# Slice the 1D array to get the elements from index 3 to 7
sliced_array = array_1d[3:8]
print("Sliced 1D array from index 3 to 7:", sliced_array)

# Access the element in the second row and third column of the 2D array
element_2d = array_2d[1, 2]
print("Element in the second row and third column of the 2D array:", element_2d)

Third element of the 1D array: 12
Sliced 1D array from index 3 to 7: [13 14 15 16 17]
Element in the second row and third column of the 2D array: 7


In [26]:
# Sum of all elements in the 1D array
sum_1d = np.sum(array_1d)
print("Sum of 1D array:", sum_1d)

# Minimum value in the 2D array
min_2d = np.min(array_2d)
print("Minimum value in the 2D array:", min_2d)

# Standard deviation of the 1D array
std_1d = np.std(array_1d)
print("Standard deviation of the 1D array:", std_1d)

Sum of 1D array: 145
Minimum value in the 2D array: 1
Standard deviation of the 1D array: 2.8722813232690143


In [27]:
# Reshape the 1D array into a 2D array with 2 rows
reshaped_array = array_1d.reshape(2, -1)
print("Reshaped 2D array:\n", reshaped_array)

# Flatten the reshaped 2D array back into a 1D array
flattened_array = reshaped_array.flatten()
print("Flattened array:", flattened_array)

Reshaped 2D array:
 [[10 11 12 13 14]
 [15 16 17 18 19]]
Flattened array: [10 11 12 13 14 15 16 17 18 19]


In [28]:
# Boolean mask for elements greater than 14
mask = array_1d > 14
print("Boolean mask for elements > 14:", mask)

# New array with only the elements greater than 14
filtered_array = array_1d[mask]
print("Filtered array with elements > 14:", filtered_array)

Boolean mask for elements > 14: [False False False False False  True  True  True  True  True]
Filtered array with elements > 14: [15 16 17 18 19]


In [35]:
4 % 2

0

In [37]:
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']